package com.example.taskmanager.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.example.taskmanager.data.model.Task
import com.example.taskmanager.data.model.TaskPriority

/**
 * Room entity representing a task stored in the local SQLite database.
 *
 * NOTE: This class lives in the data layer. UI code should use the domain
 * [Task] model from [com.example.taskmanager.data.model.Task] instead.
 *
 * The `title` field is indexed to speed up search queries.
 *
 * @property id Primary key, auto-generated by Room.
 * @property title Task title.
 * @property description Optional description.
 * @property priority Priority as an integer ordinal (mapped via [TaskPriority.ordinal]).
 * @property isCompleted 1 for completed, 0 for pending.
 * @property createdAt Creation time in epoch milliseconds.
 * @property dueDate Optional due date in epoch milliseconds, or null.
 */
@Entity(
    tableName = "tasks",
    indices = [Index(value = ["title"])]
)
data class TaskEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L,
    val title: String,
    val description: String = "",
    val priority: Int = TaskPriority.MEDIUM.ordinal,
    val isCompleted: Int = 0,
    val createdAt: Long = System.currentTimeMillis(),
    val dueDate: Long? = null
)

/**
 * Converts a Room [TaskEntity] to a domain [Task] model.
 */
fun TaskEntity.toModel(): Task = Task(
    id = id,
    title = title,
    description = description,
    priority = TaskPriority.entries.getOrElse(priority) { TaskPriority.MEDIUM },
    isCompleted = isCompleted == 1,
    createdAt = createdAt,
    dueDate = dueDate
)

/**
 * Converts a domain [Task] model to a Room [TaskEntity] for persistence.
 */
fun Task.toEntity(): TaskEntity = TaskEntity(
    id = id,
    title = title,
    description = description,
    priority = priority.ordinal,
    isCompleted = if (isCompleted) 1 else 0,
    createdAt = createdAt,
    dueDate = dueDate
)
